//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Validation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Client {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Client() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RudycommerceData.Validation.Client", typeof(Client).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to agree to the terms and conditions to be able to make this purchase..
        /// </summary>
        public static string AgreesToTermsIsTrue {
            get {
                return ResourceManager.GetString("AgreesToTermsIsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City *.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please full in an appropriate city name..
        /// </summary>
        public static string CityLength {
            get {
                return ResourceManager.GetString("CityLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A city is required to fill in..
        /// </summary>
        public static string CityReq {
            get {
                return ResourceManager.GetString("CityReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country *.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A country is required to select..
        /// </summary>
        public static string CountryCodeReq {
            get {
                return ResourceManager.GetString("CountryCodeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email *.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email address is required to fill in..
        /// </summary>
        public static string EmailReq {
            get {
                return ResourceManager.GetString("EmailReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in a possible email address..
        /// </summary>
        public static string EmailType {
            get {
                return ResourceManager.GetString("EmailType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name *.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in an appropriate first name..
        /// </summary>
        public static string FirstNameLength {
            get {
                return ResourceManager.GetString("FirstNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A first name is required to fill in..
        /// </summary>
        public static string FirstNameReq {
            get {
                return ResourceManager.GetString("FirstNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name *.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in an appropriate last name..
        /// </summary>
        public static string LastNameLength {
            get {
                return ResourceManager.GetString("LastNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A last name is required to fill in..
        /// </summary>
        public static string LastNameReq {
            get {
                return ResourceManager.GetString("LastNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail box.
        /// </summary>
        public static string MailBox {
            get {
                return ResourceManager.GetString("MailBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password *.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has to be between {0} and {1} characters long..
        /// </summary>
        public static string PasswordLengthValidation {
            get {
                return ResourceManager.GetString("PasswordLengthValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code *.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in an appropriate postal code..
        /// </summary>
        public static string PostalCodeRange {
            get {
                return ResourceManager.GetString("PostalCodeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A postal code is required to fill in..
        /// </summary>
        public static string PostalCodeReq {
            get {
                return ResourceManager.GetString("PostalCodeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street + house number *.
        /// </summary>
        public static string StreetAndNumber {
            get {
                return ResourceManager.GetString("StreetAndNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in an appropriate street name..
        /// </summary>
        public static string StreetLength {
            get {
                return ResourceManager.GetString("StreetLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert the streetname first and then the house number..
        /// </summary>
        public static string StreetRegex {
            get {
                return ResourceManager.GetString("StreetRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The street is required to fill in..
        /// </summary>
        public static string StreetReq {
            get {
                return ResourceManager.GetString("StreetReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I would like to make an account to speed up future purchases at Rudycommerce..
        /// </summary>
        public static string WantsAccountLabel {
            get {
                return ResourceManager.GetString("WantsAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I would like to subscribe to the Rudycommerce newsletter..
        /// </summary>
        public static string WantsNewsLetterLabel {
            get {
                return ResourceManager.GetString("WantsNewsLetterLabel", resourceCulture);
            }
        }
    }
}
