//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Checkout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Checkout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RudycommerceWeb.LanguageResources.Checkout", typeof(Checkout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to homepage.
        /// </summary>
        public static string BackToHomepage {
            get {
                return ResourceManager.GetString("BackToHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to homepage.
        /// </summary>
        public static string CartEmptyBackToHomepage {
            get {
                return ResourceManager.GetString("CartEmptyBackToHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your cart is empty at the moment, let&apos;s fill it back up!.
        /// </summary>
        public static string CartEmptyLetsFillIt {
            get {
                return ResourceManager.GetString("CartEmptyLetsFillIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview of your shopping cart.
        /// </summary>
        public static string CartOverviewTitle {
            get {
                return ResourceManager.GetString("CartOverviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart overview.
        /// </summary>
        public static string CartOverviewTitleShort {
            get {
                return ResourceManager.GetString("CartOverviewTitleShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No products were found.
        /// </summary>
        public static string CheckoutCartListEmpty {
            get {
                return ResourceManager.GetString("CheckoutCartListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliver to another address than your billing address?.
        /// </summary>
        public static string ChooseOtherAddressForDelivery {
            get {
                return ResourceManager.GetString("ChooseOtherAddressForDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your payment option.
        /// </summary>
        public static string ChooseYourPaymentOption {
            get {
                return ResourceManager.GetString("ChooseYourPaymentOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue shopping.
        /// </summary>
        public static string ContinueShopping {
            get {
                return ResourceManager.GetString("ContinueShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue to delivery options.
        /// </summary>
        public static string ContinueToDelivery {
            get {
                return ResourceManager.GetString("ContinueToDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue to payment.
        /// </summary>
        public static string ContinueToPayment {
            get {
                return ResourceManager.GetString("ContinueToPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue to client form.
        /// </summary>
        public static string ContinueToPersonalInfoForm {
            get {
                return ResourceManager.GetString("ContinueToPersonalInfoForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        public static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        public static string DeliveryArrow {
            get {
                return ResourceManager.GetString("DeliveryArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chosen email address is already being used. Please use another email address..
        /// </summary>
        public static string EmailNotUnique {
            get {
                return ResourceManager.GetString("EmailNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to London.
        /// </summary>
        public static string ExampleCity {
            get {
                return ResourceManager.GetString("ExampleCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to john.appleseed@rudycommerce.com.
        /// </summary>
        public static string ExampleEmail {
            get {
                return ResourceManager.GetString("ExampleEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to John.
        /// </summary>
        public static string ExampleFirstName {
            get {
                return ResourceManager.GetString("ExampleFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appleseed.
        /// </summary>
        public static string ExampleLastName {
            get {
                return ResourceManager.GetString("ExampleLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WC2N 5DU.
        /// </summary>
        public static string ExamplePostalCode {
            get {
                return ResourceManager.GetString("ExamplePostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baker Street 25.
        /// </summary>
        public static string ExampleStreetAndNumber {
            get {
                return ResourceManager.GetString("ExampleStreetAndNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g..
        /// </summary>
        public static string ForExampleABBR {
            get {
                return ResourceManager.GetString("ForExampleABBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree with the {0}. *.
        /// </summary>
        public static string IAgreeWithTermsConds {
            get {
                return ResourceManager.GetString("IAgreeWithTermsConds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with your account.
        /// </summary>
        public static string LoginFormTitle {
            get {
                return ResourceManager.GetString("LoginFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account is not required to purchase with us. &lt;br/&gt; Although with an account you can make your future purchases easier. On the next page you can create an account if you desire so..
        /// </summary>
        public static string NoAccountContent {
            get {
                return ResourceManager.GetString("NoAccountContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account?.
        /// </summary>
        public static string NoAccountTitle {
            get {
                return ResourceManager.GetString("NoAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0}, 
        ///
        ///Your order at Rudycommerce is currently being processed.
        ///We will try to do everything we can to prepare your delivery as soon as possible, so that the courrier can deliver it as soon as possible.
        ///
        ///Your ordered products:
        ///{1}
        ///Your delivery address:
        ///{2} {3}
        ///{4} {5} 
        ///
        ///Thank you for choosing us as your store,
        ///Rudycommerce
        ///.
        /// </summary>
        public static string OrderEmailContent {
            get {
                return ResourceManager.GetString("OrderEmailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order at Rudycommerce has been made.
        /// </summary>
        public static string OrderEmailTitle {
            get {
                return ResourceManager.GetString("OrderEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order finished.
        /// </summary>
        public static string OrderFinished {
            get {
                return ResourceManager.GetString("OrderFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order has succesfully been sent. Your work here is done, it&apos;s up to us now. &lt;br/&gt;&lt;br/&gt; We shall commence by carefully preparing your order, so the courier can pick it up and deliver it to your preferred location. &lt;br/&gt; &lt;br/&gt; Now you can start dreaming about what you are going to accomplish with your new gaming gear, because soon you&apos;re going to be the best in every game you&apos;ll play. &lt;br/&gt; &lt;br/&gt; Kind regards, &lt;br/&gt; Rudycommerce.
        /// </summary>
        public static string OrderFinishedThankYouText {
            get {
                return ResourceManager.GetString("OrderFinishedThankYouText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can choose another address than your billing address to deliver your order to. If you want your products delivered at your billing address, you just can continue to the next page..
        /// </summary>
        public static string OtherDeliveryAddressExplanation {
            get {
                return ResourceManager.GetString("OtherDeliveryAddressExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can choose whatever password that pleases you, if its length is between 6 and 40 characters..
        /// </summary>
        public static string PasswordExplanation {
            get {
                return ResourceManager.GetString("PasswordExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string PaymentArrow {
            get {
                return ResourceManager.GetString("PaymentArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment at Rudycommerce.
        /// </summary>
        public static string PaymentAtRudycommerce {
            get {
                return ResourceManager.GetString("PaymentAtRudycommerce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment with credit card.
        /// </summary>
        public static string PaymentWithCard {
            get {
                return ResourceManager.GetString("PaymentWithCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment with PayPal.
        /// </summary>
        public static string PaymentWithPaypal {
            get {
                return ResourceManager.GetString("PaymentWithPaypal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay using your credit card.
        /// </summary>
        public static string PayUsingCard {
            get {
                return ResourceManager.GetString("PayUsingCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal info.
        /// </summary>
        public static string PersonalInfo {
            get {
                return ResourceManager.GetString("PersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal info.
        /// </summary>
        public static string PersonalInfoArrow {
            get {
                return ResourceManager.GetString("PersonalInfoArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account yet? Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Terms and Conditions.
        /// </summary>
        public static string TermsAndConds {
            get {
                return ResourceManager.GetString("TermsAndConds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your shopping cart.
        /// </summary>
        public static string YourCart {
            get {
                return ResourceManager.GetString("YourCart", resourceCulture);
            }
        }
    }
}
