//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ImgAltTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImgAltTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RudycommerceWeb.LanguageResources.ImgAltTexts", typeof(ImgAltTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0} to cart.
        /// </summary>
        public static string AddProductToCart {
            get {
                return ResourceManager.GetString("AddProductToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to cart.
        /// </summary>
        public static string AddToCartIcon {
            get {
                return ResourceManager.GetString("AddToCartIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value: false.
        /// </summary>
        public static string FalseIcon {
            get {
                return ResourceManager.GetString("FalseIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open shopping cart.
        /// </summary>
        public static string ProgDisclShoppingCart {
            get {
                return ResourceManager.GetString("ProgDisclShoppingCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping cart.
        /// </summary>
        public static string ShoppingCart {
            get {
                return ResourceManager.GetString("ShoppingCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show next image.
        /// </summary>
        public static string ShowNextImage {
            get {
                return ResourceManager.GetString("ShowNextImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show previous image.
        /// </summary>
        public static string ShowPreviousImage {
            get {
                return ResourceManager.GetString("ShowPreviousImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported card.
        /// </summary>
        public static string SupportedCard {
            get {
                return ResourceManager.GetString("SupportedCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail.
        /// </summary>
        public static string Thumbnail {
            get {
                return ResourceManager.GetString("Thumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value: true.
        /// </summary>
        public static string TrueIcon {
            get {
                return ResourceManager.GetString("TrueIcon", resourceCulture);
            }
        }
    }
}
