//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RudycommerceLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LangResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RudycommerceLib.Properties.LangResource", typeof(LangResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoeveel voorraad is er bijgekomen?.
        /// </summary>
        public static string AddStockTitle {
            get {
                return ResourceManager.GetString("AddStockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitbreidende uitleg.
        /// </summary>
        public static string AdviceDescription {
            get {
                return ResourceManager.GetString("AdviceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merk.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuleer.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorie.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschrijving.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medewerker.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het opslaan in de databank is gefaald, gelieve te verifiëren ofdat alle gegevens correct ingevoerd zijn..
        /// </summary>
        public static string ErrSaveFailedContent {
            get {
                return ResourceManager.GetString("ErrSaveFailedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opslaan mislukt.
        /// </summary>
        public static string ErrSaveFailedTitle {
            get {
                return ResourceManager.GetString("ErrSaveFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taal.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uw ingevoerde wachtwoord en/of gebruikersnaam was verkeerd..
        /// </summary>
        public static string LoginFailedWPF {
            get {
                return ResourceManager.GetString("LoginFailedWPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bent u zeker dat u {0} &apos;{1}&apos; wil verwijderen?.
        /// </summary>
        public static string MBContentDeleteObj {
            get {
                return ResourceManager.GetString("MBContentDeleteObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bent u zeker dat u {0} de nieuwe beheerder wil maken? Indien ja, dan zal u uw rechten als beheerder verliezen en zal u opnieuw moeten inloggen..
        /// </summary>
        public static string MBContentMakeUserAdmin {
            get {
                return ResourceManager.GetString("MBContentMakeUserAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bent u zeker dat u &apos;{0}&apos; de nieuwe standaardtaal wil maken?.
        /// </summary>
        public static string MBContentNewDefaultLang {
            get {
                return ResourceManager.GetString("MBContentNewDefaultLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het opslaan van {0} is mislukt. Gelieve te controleren ofdat alles correct ingevuld is..
        /// </summary>
        public static string MBContentObjSaveFailed {
            get {
                return ResourceManager.GetString("MBContentObjSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bent u zeker dat u &apos;{0}&apos; toegang wil geven tot de applicatie?.
        /// </summary>
        public static string MBContentVerifyUser {
            get {
                return ResourceManager.GetString("MBContentVerifyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maak deze taal de nieuwe standaardtaal?.
        /// </summary>
        public static string MBContMakeLangDefault {
            get {
                return ResourceManager.GetString("MBContMakeLangDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bent u zeker dat u de applicatie wil sluiten?.
        /// </summary>
        public static string MBExitContent {
            get {
                return ResourceManager.GetString("MBExitContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicatie sluiten?.
        /// </summary>
        public static string MBExitTitle {
            get {
                return ResourceManager.GetString("MBExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwijder &apos;{0}&apos;?.
        /// </summary>
        public static string MBTitleDeleteObj {
            get {
                return ResourceManager.GetString("MBTitleDeleteObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwe standaardtaal.
        /// </summary>
        public static string MBTitleMakeLangDefault {
            get {
                return ResourceManager.GetString("MBTitleMakeLangDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} nieuwe beheerder?.
        /// </summary>
        public static string MBTitleMakeUserAdmin {
            get {
                return ResourceManager.GetString("MBTitleMakeUserAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; als standaardtaal?.
        /// </summary>
        public static string MBTitleNewDefaultLang {
            get {
                return ResourceManager.GetString("MBTitleNewDefaultLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} opslaan mislukt..
        /// </summary>
        public static string MBTitleObjSaveFailed {
            get {
                return ResourceManager.GetString("MBTitleObjSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geef &apos;{0}&apos; toegang?.
        /// </summary>
        public static string MBTitleVerifyUser {
            get {
                return ResourceManager.GetString("MBTitleVerifyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name in &quot;{0}&quot;.
        /// </summary>
        public static string NameInLanguageX {
            get {
                return ResourceManager.GetString("NameInLanguageX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nee.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen bovenliggende categorie.
        /// </summary>
        public static string NoParent {
            get {
                return ResourceManager.GetString("NoParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uw account is nog niet geverifieerd..
        /// </summary>
        public static string NotVerifiedYet {
            get {
                return ResourceManager.GetString("NotVerifiedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam in meervoud.
        /// </summary>
        public static string PluralName {
            get {
                return ResourceManager.GetString("PluralName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mogelijke waardes.
        /// </summary>
        public static string PotentialValues {
            get {
                return ResourceManager.GetString("PotentialValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De waarden ingevoerd in de tab &apos;Algemeen&apos; zijn niet allemaal (correct) ingevoerd. Gelieve deze aan te vullen vooraleer verder te gaan..
        /// </summary>
        public static string ProdFormGeneralTabInvalid {
            get {
                return ResourceManager.GetString("ProdFormGeneralTabInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productspecificatie.
        /// </summary>
        public static string Specification {
            get {
                return ResourceManager.GetString("Specification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sla op.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to het merk.
        /// </summary>
        public static string TheBrand {
            get {
                return ResourceManager.GetString("TheBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de categorie.
        /// </summary>
        public static string TheCategory {
            get {
                return ResourceManager.GetString("TheCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de medewerker.
        /// </summary>
        public static string TheEmployee {
            get {
                return ResourceManager.GetString("TheEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de taal.
        /// </summary>
        public static string TheLanguage {
            get {
                return ResourceManager.GetString("TheLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to het product.
        /// </summary>
        public static string TheProduct {
            get {
                return ResourceManager.GetString("TheProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de productspecificatie.
        /// </summary>
        public static string TheSpec {
            get {
                return ResourceManager.GetString("TheSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
